version: "3.7"

services:
  proxy:
    init: true
    build:
      context: ./Nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - ${PROXY_PORT}:80
    depends_on:
      - api
    env_file:
      - .env

  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
      target: build
    depends_on:
      - db
    command: pnpm run dev

  db:
    image: postgres:15.3
    volumes:
      - volume-blog-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data

volumes:
  volume-blog-db:
    name: ${DOMAIN_NAME}-blog-volume-db
